import type { Metadata } from "next";
import { Roboto } from "next/font/google";
import "./globals.css";
import styles from "./layout.module.css";
import MainProviders from "./providers";

const roboto = Roboto({
	weight: ["100", "300", "400", "500", "700", "900"],
	subsets: [
		"cyrillic",
		"cyrillic-ext",
		"greek",
		"greek-ext",
		"latin",
		"latin-ext",
		"vietnamese",
	],
});

export const metadata: Metadata = {
	title: "Reddit Clone",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: {
	children: React.ReactNode;
}) {
	return (
		<html lang="en">
			<body className={roboto.className}>
				<MainProviders>
					<main className={styles.main}>{children}</main>
				</MainProviders>
			</body>
		</html>
	);
}
